# Generated by Django 3.2.5 on 2021-07-09 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=16)),
                ('telefone', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=64)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=64)),
                ('numero', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=32)),
                ('cidade', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.AlterModelOptions(
            name='prestador',
            options={'verbose_name': 'Prestador de serviço', 'verbose_name_plural': 'Prestadores de serviço'},
        ),
        migrations.AddField(
            model_name='prestador',
            name='diferencial',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestador',
            name='contato',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contato'),
        ),
        migrations.AddField(
            model_name='prestador',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.endereco'),
        ),
    ]
